[package]
name = "custom_init"
version = "0.1.0"
edition = "2021"

[dependencies]
strato-sdk = { path = "../../" }
strato-core = { path = "../../crates/strato-core" }

[[bin]]
name = "custom_init"
path = "src/main.rs"